/**
 * Slim listing snapshot bundled from sister-repo `stay-cape-ann`.
 *
 * Stay Cape Ann maintains a daily-refreshed cache of every Guesty listing
 * at `data/guesty-snapshot.json` for offline resilience on the public
 * site. This module reads a stripped-down copy of that snapshot
 * (metadata only — no calendars, photos, descriptions) so Helm can
 * backfill property metadata without hitting the Guesty live API.
 *
 * Refresh: run `npm run sync-sca-listings` from the Helm repo root with
 * the stay-cape-ann repo cloned at ../../stay-cape-ann. The script
 * extracts the slim subset and writes src/data/sca-listings.json.
 *
 * Why bundled instead of HTTP-fetched: 10 listings, ~3KB. Always works
 * offline; no extra API hop or staycapeann.com dependency. Trade-off is
 * staleness if SCA refreshes and Helm doesn't re-bundle. Beds, baths,
 * lat/lng don't change often enough for that to matter; ratesy data
 * (which DOES change daily) lives elsewhere.
 */
import snapshot from '@/data/sca-listings.json';

export type ScaListing = {
  id: string;
  title: string;
  bedrooms: number;
  bathrooms: number;
  accommodates: number;
  address?: {
    city: string;
    state: string;
    full: string;
    lat?: number;
    lng?: number;
  };
  town?: string;
  propertyType?: string;
};

type Snapshot = {
  refreshedAt: string;
  source: string;
  listings: ScaListing[];
};

const data = snapshot as Snapshot;

/** ISO timestamp of when the bundled snapshot was generated by SCA. */
export const SCA_LISTINGS_REFRESHED_AT = data.refreshedAt;

/** Find a listing in the snapshot by its Guesty `_id` value. The Helm
 *  `properties.guesty_listing_id` column stores this same id, so this is
 *  the primary matcher. */
export function findScaListingByGuestyId(guestyListingId: string | null | undefined): ScaListing | null {
  if (!guestyListingId) return null;
  return data.listings.find((l) => l.id === guestyListingId) ?? null;
}

/** Address-substring fallback for properties that don't have
 *  `guesty_listing_id` set yet. Match is case-insensitive and uses the
 *  first chunk of the address (street number + name) so different
 *  formattings of the same address ("21 Horton St" vs "21 Horton Street")
 *  still resolve. Returns null when the match is ambiguous. */
export function findScaListingByAddress(address: string | null | undefined): ScaListing | null {
  if (!address) return null;
  const needle = streetKey(address);
  if (!needle) return null;
  const hits = data.listings.filter((l) => streetKey(l.address?.full ?? '') === needle);
  return hits.length === 1 ? hits[0] : null;
}

/** Reduce an address to its disambiguating street part: lowercase
 *  street number + first three street-name tokens, suffix-stripped.
 *  "21 Horton St, Gloucester, MA" → "21 horton". */
function streetKey(addr: string): string {
  const head = addr.split(',')[0]?.trim().toLowerCase() ?? '';
  return head
    .replace(/\b(st|street|rd|road|ave|avenue|ln|lane|dr|drive|blvd|boulevard|way|cir|circle|ct|court|pl|place|ter|terrace)\b\.?/g, '')
    .replace(/[^a-z0-9\s]/g, ' ')
    .trim()
    .split(/\s+/)
    .slice(0, 3)
    .join(' ');
}
