import { NextRequest, NextResponse } from 'next/server';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import crypto from 'node:crypto';
import { splitAddressLine, inferMarketFromCity } from '@/lib/inquiry-parser';
import type { Owner } from '@/lib/projections-types';
import { deriveLegacyFromOwners } from '@/lib/projections-types';

/**
 * POST /api/webhooks/inquiry
 *
 * Direct webhook from the "Schedule a call" form on risingtidestr.com
 * (rising-tide-str repo, src/app/api/schedule/route.ts). Sibling site
 * POSTs the inquiry payload in parallel with its existing Formspree
 * email send, and Helm creates a draft projection synchronously.
 *
 * This is the PRIMARY auto-create path now that we control both ends.
 * The email-parsing cron at /api/cron/import-inquiries stays as a
 * safety net for inquiries that come in through channels we don't own
 * (forwarded contact-form emails, manual referrals, etc.) and as a
 * backfill for any webhook misfires.
 *
 * Auth: shared HMAC. The sender computes
 *   hex(HMAC-SHA256(secret, raw_body))
 * and sends it in `x-helm-signature`. We compare in constant time. The
 * secret is HELM_INQUIRY_WEBHOOK_SECRET on both sides.
 *
 * Idempotency: payload carries a `request_id` (UUID generated by the
 * sender). We look it up in import_source before inserting so retries
 * don't double-create.
 */

export const runtime = 'nodejs';
export const maxDuration = 30;

type InquiryPayload = {
  request_id?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  address?: string;
  notes?: string;
  kind?: string;
  requestedDate?: string;
  requestedTime?: string;
  requestedSlot?: string;
  timezone?: string;
  submittedAt?: string;
};

let _sb: SupabaseClient | null = null;
function getSupabase(): SupabaseClient {
  if (_sb) return _sb;
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
  _sb = createClient(url, key);
  return _sb;
}

function timingSafeEqualHex(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  try {
    return crypto.timingSafeEqual(Buffer.from(a, 'hex'), Buffer.from(b, 'hex'));
  } catch {
    return false;
  }
}

function newOnboardingToken(): string {
  return crypto.randomBytes(16).toString('hex');
}

export async function POST(request: NextRequest) {
  const secret = process.env.HELM_INQUIRY_WEBHOOK_SECRET || '';
  if (!secret) {
    return NextResponse.json(
      { error: 'webhook not configured (HELM_INQUIRY_WEBHOOK_SECRET unset)' },
      { status: 503 },
    );
  }

  // Read raw body for signature verification, then JSON-parse.
  const rawBody = await request.text();
  const signature = request.headers.get('x-helm-signature') || '';
  const expected = crypto.createHmac('sha256', secret).update(rawBody).digest('hex');
  if (!signature || !timingSafeEqualHex(signature, expected)) {
    return NextResponse.json({ error: 'invalid signature' }, { status: 401 });
  }

  let body: InquiryPayload;
  try {
    body = JSON.parse(rawBody) as InquiryPayload;
  } catch {
    return NextResponse.json({ error: 'invalid json' }, { status: 400 });
  }

  const firstName = (body.firstName || '').trim();
  const lastName = (body.lastName || '').trim();
  const email = (body.email || '').trim();
  const address = (body.address || '').trim();
  if (!firstName || !email || !address) {
    return NextResponse.json(
      { error: 'missing required fields (firstName, email, address)' },
      { status: 400 },
    );
  }

  const sb = getSupabase();
  const requestId = (body.request_id || '').trim() || crypto.randomUUID();

  // Idempotency: if a projection already references this request_id,
  // return that row instead of creating a duplicate.
  const { data: existing } = await sb
    .from('projections')
    .select('id')
    .filter('import_source->>request_id', 'eq', requestId)
    .maybeSingle();
  if (existing) {
    return NextResponse.json({
      ok: true,
      projection_id: (existing as { id: string }).id,
      created: false,
      note: 'already imported',
    });
  }

  const addr = splitAddressLine(address);
  const city = addr.city || '';
  const market = inferMarketFromCity(city);
  const propertyCity = city
    ? `${city}${addr.state ? `, ${addr.state}` : ''}`
    : `${market}, MA`;

  const phone = (body.phone || '').trim();
  // The form sometimes sends "(not provided)" as a sentinel. Map that
  // (and the bare empty string) to null so the row stores clean data.
  const cleanPhone = phone && phone !== '(not provided)' ? phone : null;

  const owners: Owner[] = [{
    first_name: firstName,
    last_name: lastName,
    email,
    phone: cleanPhone,
    full_legal: null,
  }];
  const derived = deriveLegacyFromOwners(owners);

  const now = new Date();
  const presentationMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;

  const notes = (body.notes || '').trim();
  const cleanNotes = notes && notes !== '(none)' ? notes : null;

  const payload = {
    owners,
    ...derived,
    property_address: addr.street || address,
    property_city: propertyCity,
    property_type: 'House',
    market,
    bedrooms: 2,
    home_value: 0,
    neighborhood: null,
    interior_grade: null,

    mgmt_fee_pct: 0.25,
    base_cleaning: 200,
    addl_cleaning_per_br: 50,
    turnovers_per_year: 30,
    year2_growth_pct: 0.10,

    start_month: now.getMonth() + 1,
    apply_ramp: false,
    presentation_month: presentationMonth,

    initial_deposit: 2000,
    min_account_balance: 2000,
    min_availability_days: 270,
    sale_notification_days: 90,
    reputation_fee: 5000,

    status: 'draft' as const,
    onboarding_token: newOnboardingToken(),

    created_by_email: 'auto-import@helm (rt-website)',
    created_by_name: 'Auto-import',

    import_source: {
      source: 'rt_schedule_webhook',
      request_id: requestId,
      kind: body.kind || 'schedule',
      requested_slot: body.requestedSlot || null,
      timezone: body.timezone || null,
      notes: cleanNotes,
      submitted_at: body.submittedAt || now.toISOString(),
      imported_at: now.toISOString(),
    },
  };

  const { data: inserted, error: insertErr } = await sb
    .from('projections')
    .insert(payload)
    .select('id')
    .single();

  if (insertErr || !inserted) {
    return NextResponse.json(
      { error: insertErr?.message || 'insert returned no row' },
      { status: 500 },
    );
  }

  return NextResponse.json({
    ok: true,
    projection_id: (inserted as { id: string }).id,
    created: true,
  });
}
