'use client';

import { useEffect, useRef, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { Section } from '@/components/Section';
import type { Approval } from '@/lib/stay-concierge';
import {
  approveDraft,
  rejectDraft,
  coachDraft,
  markHandled,
  scheduleDraft,
  cancelSchedule,
  editDraft,
} from './actions';
import {
  prettifySlug,
  prettifyTopic,
  guestFirstFromDraft,
  ageToneColor,
  relativeTimeShort,
  formatStayDates,
  channelTone,
  proactiveKind,
  proactiveBadge,
  sendsInLabel,
} from './format';

type Props = {
  initialPending: Approval[];
};

const REFRESH_MS = 15_000;

// Muted bronze for the queued (scheduled) state. Reused from the proactive
// 'scheduled'/'reminder' badge tone on purpose, and deliberately NOT
// var(--signal) (which already means stale/aging/error on this card).
const QUEUED_TONE = '#7a6a3a';

// Quick-send presets, in minutes.
const SEND_PRESETS: { label: string; minutes: number }[] = [
  { label: 'In 10 minutes', minutes: 10 },
  { label: 'In 30 minutes', minutes: 30 },
  { label: 'In 2 hours', minutes: 120 },
];

function isoInMinutes(minutes: number): string {
  return new Date(Date.now() + minutes * 60_000).toISOString();
}

/** Build a UTC ISO from the operator's local Today/Tomorrow + HH:MM pick. */
function isoFromDayTime(day: 'today' | 'tomorrow', hhmm: string): string {
  const [h, m] = hhmm.split(':').map((n) => parseInt(n, 10));
  const d = new Date();
  if (day === 'tomorrow') d.setDate(d.getDate() + 1);
  d.setHours(h || 0, m || 0, 0, 0);
  return d.toISOString();
}

/** Default time-input value: now rounded up to the next quarter hour (local). */
function nextQuarterHour(): string {
  const d = new Date();
  d.setMinutes(Math.ceil((d.getMinutes() + 1) / 15) * 15, 0, 0);
  return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
}

export function MessagingQueue({ initialPending }: Props) {
  const router = useRouter();

  // Soft refresh on an interval so a draft generated by a webhook in the
  // last 15 seconds shows up without a manual reload.
  useEffect(() => {
    const t = setInterval(() => router.refresh(), REFRESH_MS);
    return () => clearInterval(t);
  }, [router]);

  // Queued cards float to the top, ordered by when they actually fire (the
  // countdown they show); pending drafts stay in newest-first order below.
  const queued = initialPending
    .filter((a) => a.status === 'scheduled')
    .sort((a, b) => (a.send_at || '').localeCompare(b.send_at || ''));
  const pending = initialPending.filter((a) => a.status !== 'scheduled');
  const ordered = [...queued, ...pending];
  const queuedCount = queued.length;
  const pendingCount = pending.length;
  const title =
    initialPending.length === 0
      ? 'Inbox zero'
      : pendingCount === 0
        ? `Queued (${queuedCount})`
        : `Pending (${pendingCount})${queuedCount ? ` · ${queuedCount} queued` : ''}`;

  return (
    <Section
      title={title}
      eyebrow={`refreshes every ${REFRESH_MS / 1000}s`}
      right={<RefreshChip onClick={() => router.refresh()} />}
      empty={initialPending.length === 0}
      emptyMessage="No drafts waiting. New guest messages will show up here automatically when the AI drafts a reply."
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
        {ordered.map((approval) => (
          <ApprovalCard key={approval.id} approval={approval} onResolved={() => router.refresh()} />
        ))}
      </div>
    </Section>
  );
}

function RefreshChip({ onClick }: { onClick: () => void }) {
  // Track elapsed seconds since mount, rather than a Date snapshot. Keeps
  // render pure. setInterval ticks every second; the ref is set during the
  // effect (never read during render) so the chip resets when the parent
  // remounts after a router.refresh.
  const mountedAt = useRef<number>(0);
  const [seconds, setSeconds] = useState(0);
  useEffect(() => {
    mountedAt.current = Date.now();
    const t = setInterval(() => {
      setSeconds(Math.max(0, Math.round((Date.now() - mountedAt.current) / 1000)));
    }, 1_000);
    return () => clearInterval(t);
  }, []);

  const label = seconds < 60 ? `${seconds}s ago` : `${Math.round(seconds / 60)} min ago`;
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        fontSize: 10,
        letterSpacing: '0.16em',
        textTransform: 'uppercase',
        fontWeight: 500,
        color: 'var(--ink-3)',
        background: 'transparent',
        border: '1px solid var(--rule)',
        padding: '6px 10px',
        cursor: 'pointer',
      }}
    >
      Refresh · {label}
    </button>
  );
}

// Which button on the card is currently mid-flight. Drives the per-button
// "working" label so the user can see which action they actually pressed,
// instead of every button just going equally faded via `disabled`. Stays
// set after a successful action too, so the button keeps reading as
// in-progress right up until router.refresh remounts the card.
type PendingAction =
  | 'approve'
  | 'reject'
  | 'mark-handled'
  | 'coach'
  | 'schedule'
  | 'save-edit'
  | 'cancel-schedule'
  | 'send-now'
  | null;

function ApprovalCard({
  approval,
  onResolved,
}: {
  approval: Approval;
  onResolved: () => void;
}) {
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [showCoach, setShowCoach] = useState(false);
  const [feedback, setFeedback] = useState('');
  const [pendingAction, setPendingAction] = useState<PendingAction>(null);
  // Inline edit + schedule UI. Mutually exclusive (opening one closes the
  // others) so only one drawer is ever armed at a time.
  const [editing, setEditing] = useState(false);
  const [draftText, setDraftText] = useState(approval.draft);
  const [showSchedule, setShowSchedule] = useState(false);
  const [scheduleCustom, setScheduleCustom] = useState(false);
  const [customDay, setCustomDay] = useState<'today' | 'tomorrow'>('today');
  const [customTime, setCustomTime] = useState(nextQuarterHour);
  // Queued (scheduled) cards collapse to a compact row by default so a
  // backlog of waiting sends doesn't clutter the dashboard; "Show" expands
  // one to the full draft + actions.
  const [expanded, setExpanded] = useState(false);
  const cardRef = useRef<HTMLElement | null>(null);
  // The draft text the editor was seeded from, so we can detect the AI/another
  // operator regenerating the draft underneath an open editor.
  const editBaseRef = useRef(approval.draft);
  // Last draft value we reconciled, to react when it changes in place (the card
  // is keyed by id, so router.refresh reconciles rather than remounts).
  const prevDraftRef = useRef(approval.draft);

  const isScheduled = approval.status === 'scheduled';
  // The draft changed server-side while the editor is open and the operator
  // hasn't already typed the new text: warn instead of silently overwriting.
  const draftChangedUnderEdit =
    editing && approval.draft !== editBaseRef.current && approval.draft !== draftText;

  const closeDrawers = () => {
    setShowCoach(false);
    setShowSchedule(false);
    setScheduleCustom(false);
    setEditing(false);
  };

  // Dismiss the schedule menu on Escape or a click outside this card.
  useEffect(() => {
    if (!showSchedule) return;
    const close = () => {
      setShowSchedule(false);
      setScheduleCustom(false);
    };
    const onDown = (e: MouseEvent) => {
      if (cardRef.current && !cardRef.current.contains(e.target as Node)) close();
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') close();
    };
    document.addEventListener('mousedown', onDown);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('mousedown', onDown);
      document.removeEventListener('keydown', onKey);
    };
  }, [showSchedule]);

  // The card is keyed by id, so a 15s router.refresh reconciles it in place
  // when the draft is regenerated (coach/webhook) without a remount. Keep a
  // closed editor's buffer fresh and clear the coach drawer; while the editor
  // is OPEN we deliberately leave the buffer alone and surface a conflict
  // banner (draftChangedUnderEdit) instead of clobbering the operator's text.
  useEffect(() => {
    if (prevDraftRef.current === approval.draft) return;
    prevDraftRef.current = approval.draft;
    if (isPending || editing) return;
    setDraftText(approval.draft);
    setShowCoach(false);
    setFeedback('');
  }, [approval.draft, isPending, editing]);

  const propertyLabel =
    approval.listing_name ||
    prettifySlug(approval.listing_id) ||
    'unknown property';
  const guestLabel =
    approval.guest_first ||
    guestFirstFromDraft(approval.draft) ||
    'Guest';
  const topicLabel = prettifyTopic(approval.topic) || 'General';
  const stayLabel = formatStayDates(approval.check_in, approval.check_out);
  const kind = proactiveKind(approval.guesty_message_id, approval.topic);
  const badge = proactiveBadge(kind);
  // Proactive cards have no guest message — relabel the left column so it
  // reads as the trigger/context, not "Guest said".
  const leftColumnLabel =
    kind === 'extension' ? 'Why this offer' : kind ? 'Context' : 'Guest said';

  const ageLabel =
    approval.age_minutes == null
      ? 'just now'
      : approval.age_minutes < 1
        ? 'just now'
        : approval.age_minutes < 60
          ? `${approval.age_minutes} min ago`
          : `${Math.floor(approval.age_minutes / 60)}h ${approval.age_minutes % 60}m ago`;

  // Each handler sets pendingAction BEFORE the await so the corresponding
  // button flips to its "working" label immediately. On error we clear it
  // so the buttons re-enable; on success we leave it set, because the
  // following router.refresh() will remount the list and the in-progress
  // state should read as continuous (no flicker back to "ready") until
  // that happens.
  const handleApprove = () => {
    setError(null);
    setPendingAction('approve');
    startTransition(async () => {
      const res = await approveDraft(approval.id);
      if (!res.ok) {
        // Card moved on (e.g. coaching just superseded it). Refresh to the
        // latest version instead of flashing a red error.
        if (res.stale) { onResolved(); return; }
        setError(res.error);
        setPendingAction(null);
        return;
      }
      onResolved();
    });
  };

  const handleReject = () => {
    setError(null);
    setPendingAction('reject');
    startTransition(async () => {
      const res = await rejectDraft(approval.id);
      if (!res.ok) {
        if (res.stale) { onResolved(); return; }
        setError(res.error);
        setPendingAction(null);
        return;
      }
      onResolved();
    });
  };

  const handleMarkHandled = () => {
    setError(null);
    setPendingAction('mark-handled');
    startTransition(async () => {
      const res = await markHandled(approval.id);
      if (!res.ok) {
        if (res.stale) { onResolved(); return; }
        setError(res.error);
        setPendingAction(null);
        return;
      }
      onResolved();
    });
  };

  const handleCoach = () => {
    setError(null);
    setPendingAction('coach');
    // Collapse the textarea immediately so the in-flight state reads
    // cleanly: button says "Regenerating", the inline message below
    // explains why, and the input drawer is out of the way.
    setShowCoach(false);
    startTransition(async () => {
      const res = await coachDraft(approval.id, feedback);
      if (!res.ok) {
        // Card already moved on (superseded/resolved). Refresh to the latest.
        if (res.stale) { onResolved(); return; }
        setError(res.error);
        setPendingAction(null);
        // Re-open the textarea so the user can revise their note instead
        // of having to re-type it after a transient error.
        setShowCoach(true);
        return;
      }
      setFeedback('');
      // Refresh immediately. The previous 1500ms hold was there so the
      // "Regenerating" message had time to be seen, but that message
      // already showed for the full duration of the await above (driven
      // by pendingAction === 'coach'), so we no longer need the buffer.
      onResolved();
    });
  };

  // Shared transition runner for the new actions: same stale/error/refresh
  // contract as the handlers above.
  const run = (
    action: PendingAction,
    fn: () => Promise<{ ok: true } | { ok: false; error: string; stale?: boolean }>,
    onErr?: () => void,
    onStale?: () => void,
  ) => {
    setError(null);
    setPendingAction(action);
    startTransition(async () => {
      const res = await fn();
      if (!res.ok) {
        if (res.stale) {
          // Default: the card moved on, refresh to the latest. A handler can
          // override (e.g. inline edit keeps the operator's typed text).
          if (onStale) onStale();
          else onResolved();
          return;
        }
        setError(res.error);
        setPendingAction(null);
        if (onErr) onErr();
        return;
      }
      onResolved();
    });
  };

  const handleSchedule = (sendAtIso: string) => {
    setShowSchedule(false);
    setScheduleCustom(false);
    run('schedule', () => scheduleDraft(approval.id, sendAtIso));
  };
  const handleSendNow = () => run('send-now', () => approveDraft(approval.id));
  const handleCancelSchedule = () => run('cancel-schedule', () => cancelSchedule(approval.id));
  const handleSaveEdit = () =>
    run(
      'save-edit',
      () => editDraft(approval.id, draftText),
      // Transient error: keep the editor open with the operator's text intact.
      () => setEditing(true),
      // Stale (e.g. the card was scheduled in another tab): don't silently
      // discard the typed text via a refresh. Keep it and explain.
      () => {
        setEditing(true);
        setPendingAction(null);
        setError('This draft was just queued or changed elsewhere. Copy your text, then cancel the send to keep editing.');
      },
    );

  const startEdit = () => {
    closeDrawers();
    setDraftText(approval.draft);
    editBaseRef.current = approval.draft;
    setEditing(true);
  };
  const toggleSchedule = () => {
    if (showSchedule) {
      setShowSchedule(false);
      setScheduleCustom(false);
      return;
    }
    closeDrawers();
    setShowSchedule(true);
  };
  const toggleCoach = () => {
    if (showCoach) {
      setShowCoach(false);
      return;
    }
    closeDrawers();
    setShowCoach(true);
  };

  // Collapsed queued card: a single dense row (name, channel, countdown, a
  // one-line draft preview) with its actions, so waiting sends stay quiet on
  // the dashboard. "Show" expands to the full card below.
  if (isScheduled && !expanded) {
    return (
      <article
        ref={cardRef}
        style={{
          border: '1px solid var(--rule)',
          borderLeft: `3px solid ${QUEUED_TONE}`,
          background: 'var(--paper-2)',
          padding: '11px 16px',
          display: 'flex',
          alignItems: 'center',
          gap: 10,
          flexWrap: 'wrap',
        }}
      >
        <ProactiveBadge label="Queued" tone={QUEUED_TONE} />
        <span className="font-serif" style={{ fontSize: 15, fontWeight: 500, letterSpacing: '-0.01em' }}>
          {guestLabel} · {propertyLabel}
        </span>
        {approval.channel && <ChannelBadge channel={approval.channel} />}
        <span className="eyebrow" style={{ color: 'var(--ink-3)' }} title={approval.send_at}>
          {sendsInLabel(approval.send_at)}
        </span>
        <span
          style={{
            flex: '1 1 120px',
            minWidth: 0,
            fontSize: 12,
            color: 'var(--ink-4)',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
          }}
          title={approval.draft}
        >
          {approval.draft}
        </span>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginLeft: 'auto' }}>
          <button
            type="button"
            onClick={() => setExpanded(true)}
            className="eyebrow"
            style={{ color: 'var(--ink-4)', background: 'transparent', border: 'none', padding: 0, cursor: 'pointer' }}
          >
            Show ▾
          </button>
          <SecondaryButton
            onClick={handleSendNow}
            disabled={isPending}
            loading={pendingAction === 'send-now'}
            loadingLabel="Sending"
          >
            Send now
          </SecondaryButton>
          <SecondaryButton
            onClick={handleCancelSchedule}
            disabled={isPending}
            loading={pendingAction === 'cancel-schedule'}
            loadingLabel="Cancelling"
          >
            Cancel send
          </SecondaryButton>
        </div>
        {error && (
          <p style={{ width: '100%', margin: '4px 0 0', fontSize: 12, color: 'var(--signal)', fontWeight: 500 }} role="alert">
            {error}
          </p>
        )}
      </article>
    );
  }

  return (
    <article
      ref={cardRef}
      style={{
        border: '1px solid var(--rule)',
        // A queued card wears a bronze left rule; otherwise the proactive
        // (e.g. extension-offer) accent; otherwise the plain rule.
        borderLeft: isScheduled
          ? `3px solid ${QUEUED_TONE}`
          : badge
            ? `3px solid ${badge.tone}`
            : '1px solid var(--rule)',
        background: 'var(--paper-2)',
        padding: 20,
      }}
    >
      <header
        style={{
          display: 'flex',
          alignItems: 'baseline',
          justifyContent: 'space-between',
          gap: 12,
          marginBottom: 14,
          flexWrap: 'wrap',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
          <span
            className="font-serif"
            style={{ fontSize: 18, fontWeight: 500, letterSpacing: '-0.01em' }}
          >
            {guestLabel} · {propertyLabel}
          </span>
          {approval.channel && <ChannelBadge channel={approval.channel} />}
          {stayLabel && (
            <span
              className="eyebrow"
              style={{ color: 'var(--ink-3)' }}
              title={`${approval.check_in || '?'} to ${approval.check_out || '?'}`}
            >
              {stayLabel}
            </span>
          )}
          {isScheduled ? (
            <>
              <ProactiveBadge label="Queued" tone={QUEUED_TONE} />
              <span className="eyebrow" style={{ color: 'var(--ink-3)' }} title={approval.send_at}>
                {sendsInLabel(approval.send_at)}
              </span>
            </>
          ) : badge ? (
            <ProactiveBadge label={badge.label} tone={badge.tone} />
          ) : (
            <span className="eyebrow" style={{ color: 'var(--ink-4)' }}>
              {topicLabel}
            </span>
          )}
        </div>
        {/* Queued cards suppress the "drafted X ago" cue (the countdown is the
            one time readout) and instead offer a Hide control to collapse back
            to the compact row. */}
        {isScheduled ? (
          <button
            type="button"
            onClick={() => setExpanded(false)}
            className="eyebrow"
            style={{ color: 'var(--ink-4)', background: 'transparent', border: 'none', padding: 0, cursor: 'pointer' }}
          >
            Hide ▴
          </button>
        ) : (
          <span
            className="eyebrow"
            style={{ color: 'var(--ink-4)' }}
            title={approval.created_at}
          >
            {'drafted '}
            <span
              style={{
                color: ageToneColor(approval.age_minutes),
                fontWeight: ageToneColor(approval.age_minutes) === 'var(--signal)' ? 700 : 500,
              }}
            >
              {ageLabel}
            </span>
            {' · id '}
            {approval.short_id}
          </span>
        )}
      </header>

      <div
        className="rt-msg-grid"
        style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18 }}
      >
        <FieldBlock
          label={leftColumnLabel}
          subLabel={kind ? '' : guestReceivedSubLabel(approval.guest_received_at, approval.created_at)}
          subLabelTitle={approval.guest_received_at || approval.created_at || undefined}
        >
          <BodyText>{approval.guest_text || '(empty)'}</BodyText>
        </FieldBlock>
        <FieldBlock
          label={editing ? 'Editing reply' : 'Proposed reply'}
          labelTone={editing ? 'var(--ink)' : undefined}
          action={
            !isScheduled && !editing ? (
              <button
                type="button"
                onClick={startEdit}
                disabled={isPending}
                className="eyebrow"
                style={{
                  color: 'var(--ink-4)',
                  background: 'transparent',
                  border: 'none',
                  padding: 0,
                  cursor: isPending ? 'not-allowed' : 'pointer',
                }}
                title="Edit the reply text yourself (the AI will not rewrite it)"
              >
                Edit
              </button>
            ) : null
          }
        >
          {editing ? (
            <div>
              <textarea
                value={draftText}
                onChange={(e) => setDraftText(e.target.value)}
                autoFocus
                onFocus={(e) => e.currentTarget.setSelectionRange(draftText.length, draftText.length)}
                rows={Math.max(4, Math.min(14, draftText.split('\n').length + 2))}
                style={{
                  width: '100%',
                  padding: 10,
                  // 2px ink border = "armed": this surface is what sends.
                  border: '2px solid var(--ink)',
                  background: 'var(--paper)',
                  fontFamily: 'inherit',
                  fontSize: 14,
                  lineHeight: 1.55,
                  color: 'var(--ink)',
                  resize: 'vertical',
                }}
              />
              <p style={{ margin: '8px 0 0', fontSize: 12, color: 'var(--ink-3)', fontStyle: 'italic' }}>
                You are setting the exact text that sends. The AI will not rewrite this.
              </p>
              {draftChangedUnderEdit && (
                <div style={{ marginTop: 10, padding: '8px 10px', border: '1px solid var(--signal)', background: 'var(--paper)' }}>
                  <p style={{ margin: 0, fontSize: 12, color: 'var(--signal)', fontWeight: 600 }}>
                    The AI regenerated this draft while you were editing. Saving will keep your version.
                  </p>
                  <button
                    type="button"
                    onClick={() => {
                      setDraftText(approval.draft);
                      editBaseRef.current = approval.draft;
                    }}
                    className="eyebrow"
                    style={{
                      marginTop: 4,
                      color: 'var(--ink-3)',
                      background: 'transparent',
                      border: 'none',
                      padding: 0,
                      cursor: 'pointer',
                    }}
                  >
                    Load the new draft instead (discards your changes)
                  </button>
                </div>
              )}
              <div style={{ marginTop: 10, display: 'flex', gap: 8 }}>
                <PrimaryButton
                  onClick={handleSaveEdit}
                  disabled={isPending || !draftText.trim()}
                  loading={pendingAction === 'save-edit'}
                  loadingLabel="Saving"
                >
                  Save
                </PrimaryButton>
                <SecondaryButton onClick={() => setEditing(false)} disabled={isPending}>
                  Cancel
                </SecondaryButton>
              </div>
            </div>
          ) : (
            <BodyText emphasis>{approval.draft || '(no draft)'}</BodyText>
          )}
        </FieldBlock>
      </div>

      {error && (
        <p
          style={{
            marginTop: 14,
            fontSize: 13,
            color: 'var(--signal)',
            fontWeight: 500,
          }}
          role="alert"
        >
          {error}
        </p>
      )}

      {pendingAction === 'coach' && (
        <p
          style={{
            marginTop: 14,
            fontSize: 13,
            color: 'var(--ink-3)',
            fontStyle: 'italic',
          }}
          role="status"
          aria-live="polite"
        >
          Coaching the AI with your note. The rewritten draft appears below
          in a few seconds.
        </p>
      )}

      <footer
        style={{
          marginTop: 18,
          display: 'flex',
          gap: 10,
          flexWrap: 'wrap',
          alignItems: 'center',
        }}
      >
        {isScheduled ? (
          <>
            <SecondaryButton
              onClick={handleSendNow}
              disabled={isPending}
              loading={pendingAction === 'send-now'}
              loadingLabel="Sending"
              title="Send this draft right now instead of waiting."
            >
              Send now
            </SecondaryButton>
            <SecondaryButton
              onClick={handleCancelSchedule}
              disabled={isPending}
              loading={pendingAction === 'cancel-schedule'}
              loadingLabel="Cancelling"
              title="Stop the scheduled send and return this draft to the queue."
            >
              Cancel send
            </SecondaryButton>
            <span className="eyebrow" style={{ color: 'var(--ink-4)' }}>
              Cancel send to edit or coach
            </span>
          </>
        ) : (
          <>
            <SplitSendButton
              onApprove={handleApprove}
              onToggle={toggleSchedule}
              disabled={isPending}
              loading={pendingAction === 'approve'}
              open={showSchedule}
            />
            <SecondaryButton
              onClick={toggleCoach}
              disabled={isPending}
              loading={pendingAction === 'coach'}
              loadingLabel="Regenerating"
            >
              {showCoach ? 'Cancel coaching' : 'Coach the AI'}
            </SecondaryButton>
            <SecondaryButton
              onClick={handleMarkHandled}
              disabled={isPending}
              loading={pendingAction === 'mark-handled'}
              loadingLabel="Marking"
              title="Already replied in Guesty, by phone, or otherwise. Clears the queue without sending."
            >
              Mark handled
            </SecondaryButton>
            <SecondaryButton
              onClick={handleReject}
              disabled={isPending}
              loading={pendingAction === 'reject'}
              loadingLabel="Rejecting"
              title="This guest message doesn't need a reply. Drops the draft."
            >
              Reject
            </SecondaryButton>
          </>
        )}
      </footer>

      {showSchedule && !isScheduled && (
        <SchedulePopover
          custom={scheduleCustom}
          onPreset={(minutes) => handleSchedule(isoInMinutes(minutes))}
          onOpenCustom={() => setScheduleCustom(true)}
          customDay={customDay}
          setCustomDay={setCustomDay}
          customTime={customTime}
          setCustomTime={setCustomTime}
          onConfirmCustom={() => handleSchedule(isoFromDayTime(customDay, customTime))}
          disabled={isPending}
        />
      )}

      {showCoach && (
        <div style={{ marginTop: 14 }}>
          <label
            htmlFor={`coach-${approval.id}`}
            className="eyebrow"
            style={{ display: 'block', marginBottom: 6, color: 'var(--ink-3)' }}
          >
            Coaching note
          </label>
          <textarea
            id={`coach-${approval.id}`}
            value={feedback}
            onChange={(e) => setFeedback(e.target.value)}
            placeholder="Say what's wrong with the draft. The AI will rewrite using your guidance and learn from it for next time."
            rows={3}
            style={{
              width: '100%',
              padding: 10,
              border: '1px solid var(--rule)',
              background: 'var(--paper)',
              fontFamily: 'inherit',
              fontSize: 14,
              color: 'var(--ink)',
              resize: 'vertical',
            }}
          />
          <div style={{ marginTop: 10, display: 'flex', gap: 8 }}>
            <PrimaryButton
              onClick={handleCoach}
              disabled={isPending || !feedback.trim()}
              loading={pendingAction === 'coach'}
              loadingLabel="Regenerating"
            >
              Regenerate with this note
            </PrimaryButton>
            <SecondaryButton
              onClick={() => {
                setShowCoach(false);
                setFeedback('');
              }}
              disabled={isPending}
            >
              Cancel
            </SecondaryButton>
          </div>
        </div>
      )}
    </article>
  );
}

function ProactiveBadge({ label, tone }: { label: string; tone: string }) {
  // A filled pill (vs the plain topic eyebrow) so a system-initiated card —
  // especially a revenue-bearing extension offer — is unmistakable in the
  // queue at a glance.
  return (
    <span
      style={{
        fontSize: 9,
        letterSpacing: '0.12em',
        textTransform: 'uppercase',
        fontWeight: 700,
        color: 'var(--paper)',
        background: tone,
        padding: '2px 7px',
        borderRadius: 2,
        whiteSpace: 'nowrap',
      }}
      title="System-initiated message. Review and approve before it sends"
    >
      {label}
    </span>
  );
}

function ChannelBadge({ channel }: { channel: string }) {
  return (
    <span
      style={{
        fontSize: 9,
        letterSpacing: '0.12em',
        textTransform: 'uppercase',
        fontWeight: 700,
        color: 'var(--paper)',
        background: channelTone(channel),
        padding: '2px 7px',
        borderRadius: 2,
        whiteSpace: 'nowrap',
      }}
      title={`Sent / received via ${channel}`}
    >
      {channel}
    </span>
  );
}

// Welded two-segment send control: the wide left segment is the unchanged
// one-tap "Approve & send (now)"; the narrow chevron opens the schedule
// menu. The chevron is the only new pixel on a resting card.
function SplitSendButton({
  onApprove,
  onToggle,
  disabled,
  loading,
  open,
}: {
  onApprove: () => void;
  onToggle: () => void;
  disabled?: boolean;
  loading?: boolean;
  open?: boolean;
}) {
  const seg = (extra: React.CSSProperties): React.CSSProperties => ({
    background: disabled && !loading ? 'var(--ink-4)' : 'var(--ink)',
    color: 'var(--paper)',
    border: '2px solid var(--ink)',
    fontSize: 12,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    fontWeight: 700,
    cursor: disabled ? 'not-allowed' : 'pointer',
    opacity: disabled && !loading ? 0.7 : 1,
    ...extra,
  });
  return (
    <div style={{ display: 'inline-flex' }}>
      <button
        type="button"
        onClick={onApprove}
        disabled={disabled}
        aria-busy={loading || undefined}
        style={seg({ padding: '13px 20px', borderRight: 'none' })}
      >
        {loading ? <LoadingLabel label="Sending" /> : 'Approve & send'}
      </button>
      <button
        type="button"
        onClick={onToggle}
        disabled={disabled}
        aria-haspopup="menu"
        aria-expanded={open || undefined}
        aria-label="Send later"
        title="Send later"
        style={seg({ padding: '13px 11px', borderLeft: '1px solid rgba(255,255,255,0.28)' })}
      >
        <span
          style={{
            display: 'inline-block',
            fontSize: 10,
            transform: open ? 'rotate(180deg)' : 'none',
            transition: 'transform 120ms',
          }}
        >
          ▾
        </span>
      </button>
    </div>
  );
}

// The send-later menu. Relative presets fire immediately; "At a set time"
// reveals a time + Today/Tomorrow picker in place (progressive disclosure).
function SchedulePopover({
  custom,
  onPreset,
  onOpenCustom,
  customDay,
  setCustomDay,
  customTime,
  setCustomTime,
  onConfirmCustom,
  disabled,
}: {
  custom: boolean;
  onPreset: (minutes: number) => void;
  onOpenCustom: () => void;
  customDay: 'today' | 'tomorrow';
  setCustomDay: (d: 'today' | 'tomorrow') => void;
  customTime: string;
  setCustomTime: (t: string) => void;
  onConfirmCustom: () => void;
  disabled?: boolean;
}) {
  const rowStyle: React.CSSProperties = {
    display: 'block',
    width: '100%',
    textAlign: 'left',
    background: 'transparent',
    border: 'none',
    borderBottom: '1px solid var(--rule)',
    padding: '10px 12px',
    cursor: disabled ? 'not-allowed' : 'pointer',
    fontSize: 10,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    fontWeight: 600,
    color: 'var(--ink-2)',
  };
  return (
    <div
      role="menu"
      style={{ marginTop: 10, maxWidth: 320, border: '1px solid var(--rule)', background: 'var(--paper-2)' }}
    >
      {SEND_PRESETS.map((p) => (
        <button key={p.minutes} type="button" disabled={disabled} onClick={() => onPreset(p.minutes)} style={rowStyle}>
          {p.label}
        </button>
      ))}
      {!custom ? (
        <button
          type="button"
          disabled={disabled}
          onClick={onOpenCustom}
          style={{ ...rowStyle, borderBottom: 'none', color: 'var(--ink-3)' }}
        >
          At a set time…
        </button>
      ) : (
        <div style={{ padding: 12, display: 'flex', flexDirection: 'column', gap: 10 }}>
          <div style={{ display: 'flex', gap: 6 }}>
            {(['today', 'tomorrow'] as const).map((d) => {
              const on = customDay === d;
              return (
                <button
                  key={d}
                  type="button"
                  onClick={() => setCustomDay(d)}
                  style={{
                    flex: 1,
                    padding: '7px 8px',
                    cursor: 'pointer',
                    fontSize: 10,
                    letterSpacing: '0.14em',
                    textTransform: 'uppercase',
                    fontWeight: 600,
                    border: `1px solid ${on ? 'var(--ink)' : 'var(--rule)'}`,
                    background: on ? 'var(--ink)' : 'var(--paper)',
                    color: on ? 'var(--paper)' : 'var(--ink-3)',
                  }}
                >
                  {d}
                </button>
              );
            })}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <input
              type="time"
              value={customTime}
              onChange={(e) => setCustomTime(e.target.value)}
              style={{
                width: 120,
                padding: '8px 10px',
                border: '1px solid var(--rule)',
                background: 'var(--paper)',
                fontFamily: 'inherit',
                fontSize: 14,
                color: 'var(--ink)',
              }}
            />
            <span className="eyebrow" style={{ color: 'var(--ink-4)' }} title="Eastern Time">
              ET
            </span>
          </div>
          <PrimaryButton onClick={onConfirmCustom} disabled={disabled}>
            Schedule
          </PrimaryButton>
        </div>
      )}
    </div>
  );
}

function FieldBlock({
  label,
  subLabel,
  subLabelTitle,
  labelTone,
  action,
  children,
}: {
  label: string;
  subLabel?: string;
  subLabelTitle?: string;
  labelTone?: string;
  action?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div>
      <div
        className="eyebrow"
        style={{
          marginBottom: 6,
          color: labelTone || 'var(--ink-4)',
          display: 'flex',
          alignItems: 'baseline',
          gap: 8,
          flexWrap: 'wrap',
        }}
      >
        <span>{label}</span>
        {subLabel && (
          <span
            style={{
              fontSize: 10,
              fontWeight: 400,
              letterSpacing: '0.10em',
              color: 'var(--ink-3)',
              textTransform: 'none',
            }}
            title={subLabelTitle}
          >
            {subLabel}
          </span>
        )}
        {action && <span style={{ marginLeft: 'auto' }}>{action}</span>}
      </div>
      {children}
    </div>
  );
}

/** Human-readable "sent X ago" for the GUEST SAID block. Returns '' when
 * the message arrival time isn't distinguishable from the draft time (avoid
 * redundant labels on first-draft cards where guest_sent == drafted). */
function guestReceivedSubLabel(
  guestReceivedAt: string | null,
  draftedAt: string,
): string {
  if (!guestReceivedAt) return '';
  // If the guest send and the draft are within ~90 seconds (the AI usually
  // drafts within seconds of the webhook), the timestamp adds noise. Skip
  // it. The top-right "drafted X ago" already covers that case.
  try {
    const gd = new Date(guestReceivedAt).getTime();
    const dd = draftedAt ? new Date(draftedAt).getTime() : gd;
    if (!Number.isNaN(gd) && !Number.isNaN(dd) && Math.abs(dd - gd) < 90_000) {
      return '';
    }
  } catch {
    // fall through
  }
  const rel = relativeTimeShort(guestReceivedAt);
  return rel ? `sent ${rel}` : '';
}

function BodyText({ children, emphasis = false }: { children: React.ReactNode; emphasis?: boolean }) {
  return (
    <p
      style={{
        margin: 0,
        fontSize: 14,
        lineHeight: 1.55,
        color: emphasis ? 'var(--ink)' : 'var(--ink-2)',
        whiteSpace: 'pre-wrap',
        fontWeight: emphasis ? 500 : 400,
      }}
    >
      {children}
    </p>
  );
}

function PrimaryButton({
  children,
  onClick,
  disabled,
  loading,
  loadingLabel,
}: {
  children: React.ReactNode;
  onClick: () => void;
  disabled?: boolean;
  loading?: boolean;
  loadingLabel?: string;
}) {
  // When this button is the one doing work, keep it dark + full opacity
  // (so it reads as the active surface, not as "disabled like the others")
  // and swap the label for "<loadingLabel>" + animated dots.
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      aria-busy={loading || undefined}
      style={{
        // The loading button keeps full ink; only the non-loading
        // buttons fade to ink-4 while another action runs.
        background: disabled && !loading ? 'var(--ink-4)' : 'var(--ink)',
        color: 'var(--paper)',
        border: '2px solid var(--ink)',
        padding: '13px 22px',
        fontSize: 12,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        fontWeight: 700,
        cursor: disabled ? 'not-allowed' : 'pointer',
        opacity: disabled && !loading ? 0.7 : 1,
      }}
    >
      {loading ? <LoadingLabel label={loadingLabel || 'Working'} /> : children}
    </button>
  );
}

function SecondaryButton({
  children,
  onClick,
  disabled,
  loading,
  loadingLabel,
  title,
}: {
  children: React.ReactNode;
  onClick: () => void;
  disabled?: boolean;
  loading?: boolean;
  loadingLabel?: string;
  title?: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      aria-busy={loading || undefined}
      title={title}
      style={{
        background: loading ? 'var(--paper-2)' : 'var(--paper)',
        color: loading ? 'var(--ink)' : 'var(--ink-2)',
        border: loading ? '1px solid var(--ink)' : '1px solid var(--ink-3)',
        padding: '10px 16px',
        fontSize: 11,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        fontWeight: 500,
        cursor: disabled ? 'not-allowed' : 'pointer',
        // The loading button stays full opacity; only the non-loading
        // buttons fade while another action runs.
        opacity: disabled && !loading ? 0.5 : 1,
      }}
    >
      {loading ? <LoadingLabel label={loadingLabel || 'Working'} /> : children}
    </button>
  );
}

// Inline working indicator: the action verb (e.g. "Sending") followed by
// three pulsing dots. Used inside the primary/secondary buttons so the
// user can see exactly which action is in-flight instead of every button
// just looking equally faded.
function LoadingLabel({ label }: { label: string }) {
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center' }}>
      {label}
      <span aria-hidden="true" style={{ display: 'inline-flex', alignItems: 'center', marginLeft: 6, gap: 3 }}>
        <span className="rt-loading-dot" />
        <span className="rt-loading-dot" />
        <span className="rt-loading-dot" />
      </span>
    </span>
  );
}
