'use client';

import { useEffect, useRef, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { Section } from '@/components/Section';
import type { Approval } from '@/lib/stay-concierge';
import { approveDraft, rejectDraft, coachDraft, markHandled } from './actions';
import {
  prettifySlug,
  prettifyTopic,
  guestFirstFromDraft,
  ageToneColor,
  relativeTimeShort,
  formatStayDates,
  channelTone,
} from './format';

type Props = {
  initialPending: Approval[];
};

const REFRESH_MS = 15_000;

export function MessagingQueue({ initialPending }: Props) {
  const router = useRouter();

  // Soft refresh on an interval so a draft generated by a webhook in the
  // last 15 seconds shows up without a manual reload.
  useEffect(() => {
    const t = setInterval(() => router.refresh(), REFRESH_MS);
    return () => clearInterval(t);
  }, [router]);

  return (
    <Section
      title={initialPending.length === 0 ? 'Inbox zero' : `Pending (${initialPending.length})`}
      eyebrow={`refreshes every ${REFRESH_MS / 1000}s`}
      right={<RefreshChip onClick={() => router.refresh()} />}
      empty={initialPending.length === 0}
      emptyMessage="No drafts waiting. New guest messages will show up here automatically when the AI drafts a reply."
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
        {initialPending.map((approval) => (
          <ApprovalCard key={approval.id} approval={approval} onResolved={() => router.refresh()} />
        ))}
      </div>
    </Section>
  );
}

function RefreshChip({ onClick }: { onClick: () => void }) {
  // Track elapsed seconds since mount, rather than a Date snapshot. Keeps
  // render pure. setInterval ticks every second; the ref is set during the
  // effect (never read during render) so the chip resets when the parent
  // remounts after a router.refresh.
  const mountedAt = useRef<number>(0);
  const [seconds, setSeconds] = useState(0);
  useEffect(() => {
    mountedAt.current = Date.now();
    const t = setInterval(() => {
      setSeconds(Math.max(0, Math.round((Date.now() - mountedAt.current) / 1000)));
    }, 1_000);
    return () => clearInterval(t);
  }, []);

  const label = seconds < 60 ? `${seconds}s ago` : `${Math.round(seconds / 60)} min ago`;
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        fontSize: 10,
        letterSpacing: '0.16em',
        textTransform: 'uppercase',
        fontWeight: 500,
        color: 'var(--ink-3)',
        background: 'transparent',
        border: '1px solid var(--rule)',
        padding: '6px 10px',
        cursor: 'pointer',
      }}
    >
      Refresh · {label}
    </button>
  );
}

// Which button on the card is currently mid-flight. Drives the per-button
// "working" label so the user can see which action they actually pressed,
// instead of every button just going equally faded via `disabled`. Stays
// set after a successful action too, so the button keeps reading as
// in-progress right up until router.refresh remounts the card.
type PendingAction = 'approve' | 'reject' | 'mark-handled' | 'coach' | null;

function ApprovalCard({
  approval,
  onResolved,
}: {
  approval: Approval;
  onResolved: () => void;
}) {
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [showCoach, setShowCoach] = useState(false);
  const [feedback, setFeedback] = useState('');
  const [pendingAction, setPendingAction] = useState<PendingAction>(null);

  const propertyLabel =
    approval.listing_name ||
    prettifySlug(approval.listing_id) ||
    'unknown property';
  const guestLabel =
    approval.guest_first ||
    guestFirstFromDraft(approval.draft) ||
    'Guest';
  const topicLabel = prettifyTopic(approval.topic) || 'General';
  const stayLabel = formatStayDates(approval.check_in, approval.check_out);

  const ageLabel =
    approval.age_minutes == null
      ? 'just now'
      : approval.age_minutes < 1
        ? 'just now'
        : approval.age_minutes < 60
          ? `${approval.age_minutes} min ago`
          : `${Math.floor(approval.age_minutes / 60)}h ${approval.age_minutes % 60}m ago`;

  // Each handler sets pendingAction BEFORE the await so the corresponding
  // button flips to its "working" label immediately. On error we clear it
  // so the buttons re-enable; on success we leave it set, because the
  // following router.refresh() will remount the list and the in-progress
  // state should read as continuous (no flicker back to "ready") until
  // that happens.
  const handleApprove = () => {
    setError(null);
    setPendingAction('approve');
    startTransition(async () => {
      const res = await approveDraft(approval.id);
      if (!res.ok) {
        setError(res.error);
        setPendingAction(null);
        return;
      }
      onResolved();
    });
  };

  const handleReject = () => {
    setError(null);
    setPendingAction('reject');
    startTransition(async () => {
      const res = await rejectDraft(approval.id);
      if (!res.ok) {
        setError(res.error);
        setPendingAction(null);
        return;
      }
      onResolved();
    });
  };

  const handleMarkHandled = () => {
    setError(null);
    setPendingAction('mark-handled');
    startTransition(async () => {
      const res = await markHandled(approval.id);
      if (!res.ok) {
        setError(res.error);
        setPendingAction(null);
        return;
      }
      onResolved();
    });
  };

  const handleCoach = () => {
    setError(null);
    setPendingAction('coach');
    // Collapse the textarea immediately so the in-flight state reads
    // cleanly: button says "Regenerating", the inline message below
    // explains why, and the input drawer is out of the way.
    setShowCoach(false);
    startTransition(async () => {
      const res = await coachDraft(approval.id, feedback);
      if (!res.ok) {
        setError(res.error);
        setPendingAction(null);
        // Re-open the textarea so the user can revise their note instead
        // of having to re-type it after a transient error.
        setShowCoach(true);
        return;
      }
      setFeedback('');
      // Refresh immediately. The previous 1500ms hold was there so the
      // "Regenerating" message had time to be seen, but that message
      // already showed for the full duration of the await above (driven
      // by pendingAction === 'coach'), so we no longer need the buffer.
      onResolved();
    });
  };

  return (
    <article
      style={{
        border: '1px solid var(--rule)',
        background: 'var(--paper-2)',
        padding: 20,
      }}
    >
      <header
        style={{
          display: 'flex',
          alignItems: 'baseline',
          justifyContent: 'space-between',
          gap: 12,
          marginBottom: 14,
          flexWrap: 'wrap',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
          <span
            className="font-serif"
            style={{ fontSize: 18, fontWeight: 500, letterSpacing: '-0.01em' }}
          >
            {guestLabel} · {propertyLabel}
          </span>
          {approval.channel && <ChannelBadge channel={approval.channel} />}
          {stayLabel && (
            <span
              className="eyebrow"
              style={{ color: 'var(--ink-3)' }}
              title={`${approval.check_in || '?'} to ${approval.check_out || '?'}`}
            >
              {stayLabel}
            </span>
          )}
          <span className="eyebrow" style={{ color: 'var(--ink-4)' }}>
            {topicLabel}
          </span>
        </div>
        <span
          className="eyebrow"
          style={{ color: 'var(--ink-4)' }}
          title={approval.created_at}
        >
          {'drafted '}
          <span
            style={{
              color: ageToneColor(approval.age_minutes),
              fontWeight: ageToneColor(approval.age_minutes) === 'var(--signal)' ? 700 : 500,
            }}
          >
            {ageLabel}
          </span>
          {' · id '}
          {approval.short_id}
        </span>
      </header>

      <div
        className="rt-msg-grid"
        style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18 }}
      >
        <FieldBlock
          label="Guest said"
          subLabel={guestReceivedSubLabel(approval.guest_received_at, approval.created_at)}
          subLabelTitle={approval.guest_received_at || approval.created_at || undefined}
        >
          <BodyText>{approval.guest_text || '(empty)'}</BodyText>
        </FieldBlock>
        <FieldBlock label="Proposed reply">
          <BodyText emphasis>{approval.draft || '(no draft)'}</BodyText>
        </FieldBlock>
      </div>

      {error && (
        <p
          style={{
            marginTop: 14,
            fontSize: 13,
            color: 'var(--signal)',
            fontWeight: 500,
          }}
          role="alert"
        >
          {error}
        </p>
      )}

      {pendingAction === 'coach' && (
        <p
          style={{
            marginTop: 14,
            fontSize: 13,
            color: 'var(--ink-3)',
            fontStyle: 'italic',
          }}
          role="status"
          aria-live="polite"
        >
          Coaching the AI with your note. The rewritten draft appears below
          in a few seconds.
        </p>
      )}

      <footer
        style={{
          marginTop: 18,
          display: 'flex',
          gap: 10,
          flexWrap: 'wrap',
          alignItems: 'center',
        }}
      >
        <PrimaryButton
          onClick={handleApprove}
          disabled={isPending}
          loading={pendingAction === 'approve'}
          loadingLabel="Sending"
        >
          Approve & send
        </PrimaryButton>
        <SecondaryButton
          onClick={() => setShowCoach((v) => !v)}
          disabled={isPending}
          loading={pendingAction === 'coach'}
          loadingLabel="Regenerating"
        >
          {showCoach ? 'Cancel coaching' : 'Coach the AI'}
        </SecondaryButton>
        <SecondaryButton
          onClick={handleMarkHandled}
          disabled={isPending}
          loading={pendingAction === 'mark-handled'}
          loadingLabel="Marking"
          title="Already replied in Guesty, by phone, or otherwise. Clears the queue without sending."
        >
          Mark handled
        </SecondaryButton>
        <SecondaryButton
          onClick={handleReject}
          disabled={isPending}
          loading={pendingAction === 'reject'}
          loadingLabel="Rejecting"
          title="This guest message doesn't need a reply. Drops the draft."
        >
          Reject
        </SecondaryButton>
      </footer>

      {showCoach && (
        <div style={{ marginTop: 14 }}>
          <label
            htmlFor={`coach-${approval.id}`}
            className="eyebrow"
            style={{ display: 'block', marginBottom: 6, color: 'var(--ink-3)' }}
          >
            Coaching note
          </label>
          <textarea
            id={`coach-${approval.id}`}
            value={feedback}
            onChange={(e) => setFeedback(e.target.value)}
            placeholder="Say what's wrong with the draft. The AI will rewrite using your guidance and learn from it for next time."
            rows={3}
            style={{
              width: '100%',
              padding: 10,
              border: '1px solid var(--rule)',
              background: 'var(--paper)',
              fontFamily: 'inherit',
              fontSize: 14,
              color: 'var(--ink)',
              resize: 'vertical',
            }}
          />
          <div style={{ marginTop: 10, display: 'flex', gap: 8 }}>
            <PrimaryButton
              onClick={handleCoach}
              disabled={isPending || !feedback.trim()}
              loading={pendingAction === 'coach'}
              loadingLabel="Regenerating"
            >
              Regenerate with this note
            </PrimaryButton>
            <SecondaryButton
              onClick={() => {
                setShowCoach(false);
                setFeedback('');
              }}
              disabled={isPending}
            >
              Cancel
            </SecondaryButton>
          </div>
        </div>
      )}
    </article>
  );
}

function ChannelBadge({ channel }: { channel: string }) {
  return (
    <span
      style={{
        fontSize: 9,
        letterSpacing: '0.12em',
        textTransform: 'uppercase',
        fontWeight: 700,
        color: 'var(--paper)',
        background: channelTone(channel),
        padding: '2px 7px',
        borderRadius: 2,
        whiteSpace: 'nowrap',
      }}
      title={`Sent / received via ${channel}`}
    >
      {channel}
    </span>
  );
}

function FieldBlock({
  label,
  subLabel,
  subLabelTitle,
  children,
}: {
  label: string;
  subLabel?: string;
  subLabelTitle?: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <div
        className="eyebrow"
        style={{
          marginBottom: 6,
          color: 'var(--ink-4)',
          display: 'flex',
          alignItems: 'baseline',
          gap: 8,
          flexWrap: 'wrap',
        }}
      >
        <span>{label}</span>
        {subLabel && (
          <span
            style={{
              fontSize: 10,
              fontWeight: 400,
              letterSpacing: '0.10em',
              color: 'var(--ink-3)',
              textTransform: 'none',
            }}
            title={subLabelTitle}
          >
            {subLabel}
          </span>
        )}
      </div>
      {children}
    </div>
  );
}

/** Human-readable "sent X ago" for the GUEST SAID block. Returns '' when
 * the message arrival time isn't distinguishable from the draft time (avoid
 * redundant labels on first-draft cards where guest_sent == drafted). */
function guestReceivedSubLabel(
  guestReceivedAt: string | null,
  draftedAt: string,
): string {
  if (!guestReceivedAt) return '';
  // If the guest send and the draft are within ~90 seconds (the AI usually
  // drafts within seconds of the webhook), the timestamp adds noise. Skip
  // it. The top-right "drafted X ago" already covers that case.
  try {
    const gd = new Date(guestReceivedAt).getTime();
    const dd = draftedAt ? new Date(draftedAt).getTime() : gd;
    if (!Number.isNaN(gd) && !Number.isNaN(dd) && Math.abs(dd - gd) < 90_000) {
      return '';
    }
  } catch {
    // fall through
  }
  const rel = relativeTimeShort(guestReceivedAt);
  return rel ? `sent ${rel}` : '';
}

function BodyText({ children, emphasis = false }: { children: React.ReactNode; emphasis?: boolean }) {
  return (
    <p
      style={{
        margin: 0,
        fontSize: 14,
        lineHeight: 1.55,
        color: emphasis ? 'var(--ink)' : 'var(--ink-2)',
        whiteSpace: 'pre-wrap',
        fontWeight: emphasis ? 500 : 400,
      }}
    >
      {children}
    </p>
  );
}

function PrimaryButton({
  children,
  onClick,
  disabled,
  loading,
  loadingLabel,
}: {
  children: React.ReactNode;
  onClick: () => void;
  disabled?: boolean;
  loading?: boolean;
  loadingLabel?: string;
}) {
  // When this button is the one doing work, keep it dark + full opacity
  // (so it reads as the active surface, not as "disabled like the others")
  // and swap the label for "<loadingLabel>" + animated dots.
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      aria-busy={loading || undefined}
      style={{
        // The loading button keeps full ink; only the non-loading
        // buttons fade to ink-4 while another action runs.
        background: disabled && !loading ? 'var(--ink-4)' : 'var(--ink)',
        color: 'var(--paper)',
        border: '2px solid var(--ink)',
        padding: '13px 22px',
        fontSize: 12,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        fontWeight: 700,
        cursor: disabled ? 'not-allowed' : 'pointer',
        opacity: disabled && !loading ? 0.7 : 1,
      }}
    >
      {loading ? <LoadingLabel label={loadingLabel || 'Working'} /> : children}
    </button>
  );
}

function SecondaryButton({
  children,
  onClick,
  disabled,
  loading,
  loadingLabel,
  title,
}: {
  children: React.ReactNode;
  onClick: () => void;
  disabled?: boolean;
  loading?: boolean;
  loadingLabel?: string;
  title?: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      aria-busy={loading || undefined}
      title={title}
      style={{
        background: loading ? 'var(--paper-2)' : 'var(--paper)',
        color: loading ? 'var(--ink)' : 'var(--ink-2)',
        border: loading ? '1px solid var(--ink)' : '1px solid var(--ink-3)',
        padding: '10px 16px',
        fontSize: 11,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        fontWeight: 500,
        cursor: disabled ? 'not-allowed' : 'pointer',
        // The loading button stays full opacity; only the non-loading
        // buttons fade while another action runs.
        opacity: disabled && !loading ? 0.5 : 1,
      }}
    >
      {loading ? <LoadingLabel label={loadingLabel || 'Working'} /> : children}
    </button>
  );
}

// Inline working indicator: the action verb (e.g. "Sending") followed by
// three pulsing dots. Used inside the primary/secondary buttons so the
// user can see exactly which action is in-flight instead of every button
// just looking equally faded.
function LoadingLabel({ label }: { label: string }) {
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center' }}>
      {label}
      <span aria-hidden="true" style={{ display: 'inline-flex', alignItems: 'center', marginLeft: 6, gap: 3 }}>
        <span className="rt-loading-dot" />
        <span className="rt-loading-dot" />
        <span className="rt-loading-dot" />
      </span>
    </span>
  );
}
