'use client';

import { useEffect, useRef, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { Section } from '@/components/Section';
import type { Approval } from '@/lib/stay-concierge';
import { approveDraft, rejectDraft, coachDraft, markHandled } from './actions';

type Props = {
  initialPending: Approval[];
};

const REFRESH_MS = 15_000;

export function MessagingQueue({ initialPending }: Props) {
  const router = useRouter();

  // Soft refresh on an interval so a draft generated by a webhook in the
  // last 15 seconds shows up without a manual reload.
  useEffect(() => {
    const t = setInterval(() => router.refresh(), REFRESH_MS);
    return () => clearInterval(t);
  }, [router]);

  return (
    <Section
      title={initialPending.length === 0 ? 'Inbox zero' : `Pending (${initialPending.length})`}
      eyebrow={`refreshes every ${REFRESH_MS / 1000}s`}
      right={<RefreshChip onClick={() => router.refresh()} />}
      empty={initialPending.length === 0}
      emptyMessage="No drafts waiting. New guest messages will show up here automatically when the AI drafts a reply."
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
        {initialPending.map((approval) => (
          <ApprovalCard key={approval.id} approval={approval} onResolved={() => router.refresh()} />
        ))}
      </div>
    </Section>
  );
}

function RefreshChip({ onClick }: { onClick: () => void }) {
  // Track elapsed seconds since mount, rather than a Date snapshot. Keeps
  // render pure. setInterval ticks every second; the ref is set during the
  // effect (never read during render) so the chip resets when the parent
  // remounts after a router.refresh.
  const mountedAt = useRef<number>(0);
  const [seconds, setSeconds] = useState(0);
  useEffect(() => {
    mountedAt.current = Date.now();
    const t = setInterval(() => {
      setSeconds(Math.max(0, Math.round((Date.now() - mountedAt.current) / 1000)));
    }, 1_000);
    return () => clearInterval(t);
  }, []);

  const label = seconds < 60 ? `${seconds}s ago` : `${Math.round(seconds / 60)} min ago`;
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        fontSize: 10,
        letterSpacing: '0.16em',
        textTransform: 'uppercase',
        fontWeight: 500,
        color: 'var(--ink-3)',
        background: 'transparent',
        border: '1px solid var(--rule)',
        padding: '6px 10px',
        cursor: 'pointer',
      }}
    >
      Refresh · {label}
    </button>
  );
}

function ApprovalCard({
  approval,
  onResolved,
}: {
  approval: Approval;
  onResolved: () => void;
}) {
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [showCoach, setShowCoach] = useState(false);
  const [feedback, setFeedback] = useState('');
  const [coachQueued, setCoachQueued] = useState(false);

  const propertyLabel = approval.listing_name || approval.listing_id || 'unknown property';
  const guestLabel = approval.guest_first || 'Guest';
  const topicLabel = approval.topic || 'general';

  const ageLabel =
    approval.age_minutes == null
      ? 'just now'
      : approval.age_minutes < 1
        ? 'just now'
        : approval.age_minutes < 60
          ? `${approval.age_minutes} min ago`
          : `${Math.floor(approval.age_minutes / 60)}h ${approval.age_minutes % 60}m ago`;

  const handleApprove = () => {
    setError(null);
    startTransition(async () => {
      const res = await approveDraft(approval.id);
      if (!res.ok) {
        setError(res.error);
        return;
      }
      onResolved();
    });
  };

  const handleReject = () => {
    setError(null);
    startTransition(async () => {
      const res = await rejectDraft(approval.id);
      if (!res.ok) {
        setError(res.error);
        return;
      }
      onResolved();
    });
  };

  const handleMarkHandled = () => {
    setError(null);
    startTransition(async () => {
      const res = await markHandled(approval.id);
      if (!res.ok) {
        setError(res.error);
        return;
      }
      onResolved();
    });
  };

  const handleCoach = () => {
    setError(null);
    startTransition(async () => {
      const res = await coachDraft(approval.id, feedback);
      if (!res.ok) {
        setError(res.error);
        return;
      }
      setCoachQueued(true);
      setFeedback('');
      setShowCoach(false);
      setTimeout(() => {
        setCoachQueued(false);
        onResolved();
      }, 1500);
    });
  };

  return (
    <article
      style={{
        border: '1px solid var(--rule)',
        background: 'var(--paper-2)',
        padding: 20,
      }}
    >
      <header
        style={{
          display: 'flex',
          alignItems: 'baseline',
          justifyContent: 'space-between',
          gap: 12,
          marginBottom: 14,
          flexWrap: 'wrap',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
          <span
            className="font-serif"
            style={{ fontSize: 18, fontWeight: 500, letterSpacing: '-0.01em' }}
          >
            {guestLabel} · {propertyLabel}
          </span>
          <span className="eyebrow" style={{ color: 'var(--ink-4)' }}>
            {topicLabel}
          </span>
        </div>
        <span className="eyebrow" style={{ color: 'var(--ink-4)' }}>
          {ageLabel} · id {approval.short_id}
        </span>
      </header>

      <div
        className="rt-msg-grid"
        style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18 }}
      >
        <FieldBlock label="Guest said">
          <BodyText>{approval.guest_text || '(empty)'}</BodyText>
        </FieldBlock>
        <FieldBlock label="Proposed reply">
          <BodyText emphasis>{approval.draft || '(no draft)'}</BodyText>
        </FieldBlock>
      </div>

      {error && (
        <p
          style={{
            marginTop: 14,
            fontSize: 13,
            color: 'var(--signal)',
            fontWeight: 500,
          }}
          role="alert"
        >
          {error}
        </p>
      )}

      {coachQueued && (
        <p
          style={{
            marginTop: 14,
            fontSize: 13,
            color: 'var(--ink-3)',
            fontStyle: 'italic',
          }}
        >
          Regenerating with your coaching. New draft appears below in a few seconds.
        </p>
      )}

      <footer
        style={{
          marginTop: 18,
          display: 'flex',
          gap: 10,
          flexWrap: 'wrap',
          alignItems: 'center',
        }}
      >
        <PrimaryButton onClick={handleApprove} disabled={isPending}>
          Approve & send
        </PrimaryButton>
        <SecondaryButton onClick={() => setShowCoach((v) => !v)} disabled={isPending}>
          {showCoach ? 'Cancel coaching' : 'Coach the AI'}
        </SecondaryButton>
        <SecondaryButton
          onClick={handleMarkHandled}
          disabled={isPending}
          title="Already replied in Guesty, by phone, or otherwise. Clears the queue without sending."
        >
          Mark handled
        </SecondaryButton>
        <SecondaryButton
          onClick={handleReject}
          disabled={isPending}
          title="This guest message doesn't need a reply. Drops the draft."
        >
          Reject
        </SecondaryButton>
      </footer>

      {showCoach && (
        <div style={{ marginTop: 14 }}>
          <label
            htmlFor={`coach-${approval.id}`}
            className="eyebrow"
            style={{ display: 'block', marginBottom: 6, color: 'var(--ink-3)' }}
          >
            Coaching note
          </label>
          <textarea
            id={`coach-${approval.id}`}
            value={feedback}
            onChange={(e) => setFeedback(e.target.value)}
            placeholder="Say what's wrong with the draft. The AI will rewrite using your guidance and learn from it for next time."
            rows={3}
            style={{
              width: '100%',
              padding: 10,
              border: '1px solid var(--rule)',
              background: 'var(--paper)',
              fontFamily: 'inherit',
              fontSize: 14,
              color: 'var(--ink)',
              resize: 'vertical',
            }}
          />
          <div style={{ marginTop: 10, display: 'flex', gap: 8 }}>
            <PrimaryButton onClick={handleCoach} disabled={isPending || !feedback.trim()}>
              Regenerate with this note
            </PrimaryButton>
            <SecondaryButton
              onClick={() => {
                setShowCoach(false);
                setFeedback('');
              }}
              disabled={isPending}
            >
              Cancel
            </SecondaryButton>
          </div>
        </div>
      )}
    </article>
  );
}

function FieldBlock({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="eyebrow" style={{ marginBottom: 6, color: 'var(--ink-4)' }}>
        {label}
      </div>
      {children}
    </div>
  );
}

function BodyText({ children, emphasis = false }: { children: React.ReactNode; emphasis?: boolean }) {
  return (
    <p
      style={{
        margin: 0,
        fontSize: 14,
        lineHeight: 1.55,
        color: emphasis ? 'var(--ink)' : 'var(--ink-2)',
        whiteSpace: 'pre-wrap',
        fontWeight: emphasis ? 500 : 400,
      }}
    >
      {children}
    </p>
  );
}

function PrimaryButton({
  children,
  onClick,
  disabled,
}: {
  children: React.ReactNode;
  onClick: () => void;
  disabled?: boolean;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      style={{
        background: disabled ? 'var(--ink-4)' : 'var(--ink)',
        color: 'var(--paper)',
        border: 'none',
        padding: '10px 16px',
        fontSize: 11,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        fontWeight: 600,
        cursor: disabled ? 'not-allowed' : 'pointer',
        opacity: disabled ? 0.7 : 1,
      }}
    >
      {children}
    </button>
  );
}

function SecondaryButton({
  children,
  onClick,
  disabled,
  title,
}: {
  children: React.ReactNode;
  onClick: () => void;
  disabled?: boolean;
  title?: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      title={title}
      style={{
        background: 'var(--paper)',
        color: 'var(--ink)',
        border: '1px solid var(--ink)',
        padding: '10px 16px',
        fontSize: 11,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        fontWeight: 600,
        cursor: disabled ? 'not-allowed' : 'pointer',
        opacity: disabled ? 0.5 : 1,
      }}
    >
      {children}
    </button>
  );
}
